[github]
# Github API token used for interacting with the Github web API
# requires creating personal access token with Full `repo` scope
github-api-token = ""

# Webhook secret used to verify webhooks originated from Github
webhook-secret = ""

[git]

# file where an SSH private key lives, needed for fetching/pushing
# corresponding public key must be added to github account
ssh-key-file = ""

# The name+email used for creating commits
user = ""
email = ""

# An array of repository configs
[[repo]]

# Identify which repository is being managed:
#   github.com/<owner>/<name>
owner = ""
name = ""

# Require an approving Github review before a PR can be landed
# require-review = true

# Enforce that maintainer-mode is used so that PRs are updated in-place before merging
# maintainer-mode = true

# Time that bors will wait before giving up on CI completing
# timeout-seconds = <seconds>

# Github checks and status's, or workflows required to pass on the `auto` branch before merging a PR
checks = [
    "",
]
